config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat rabbit snake racoon lizard)
  validates :name, presence: true
  validates :species, inclusion: {in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params 
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1631</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>

<%= form_with model: @pet do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<h1>Pets</h1>

<% @pets.each do |pet| %>
  <p> <%= link_to pet.name, pet_path(pet)  %> </p>
<% end %>

<%= link_to "Add a pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>Add Pet</h1>

<%= form_with model: @pet do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1> <%= @pet.name %></h1>
<p> <%= @pet.address %></p>
<p> <%= @pet.species%></p>
<p> <%= @pet.found_on %></p>

<%= link_to "back", pets_path %>
<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Delete", pet_path(@pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>